version: "3"
services:
  flask-app:
    build: ./tomato-app
    environment:
      - SECRET=${SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_DATASET_PATH=${S3_DATASET_PATH}
      - S3_NEW_IMAGES_PATH=${S3_NEW_IMAGES_PATH}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - LABEL_STUDIO_URL=${LABEL_STUDIO_URL}
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - "~/.aws:/root/.aws"
      - migrations_data:/tomato/migrations
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
    depends_on:
      - label-studio
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

  label-studio:
    build: ./label-studio
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
      - ALLOWED_HOSTS=label-studio,localhost,127.0.0.1
    volumes:
      - label_studio_data:/label-studio/data


networks:
  mynetwork:

volumes:
  postgres-data:
    driver: local
  migrations_data:
    driver: local
  label_studio_data:
    driver: local